language: node_js
node_js:
  - '6'

before_install:
  - time npm i -g yarn --cache-min 999999999

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache
    - $HOME/.npm

install:
  - time yarn

script:
  - time yarn run build

deploy:
- provider: gcs
  access_key_id: GOOGZMKOTXLFVL5ERT2T
  secret_access_key:
    secure: YwzUJusZSJHuiNvCMlNgK710jZDT8hHmh2agrNhysKBkMgZYWlVkN1nQZDYZ8zR7qLXqEVBWzuXasAFGXE7/GESt/tT08pklXIT5Lj+VwHMqZChmu80OTBggYn1oop4V/S2aRAc0pgCfnuqsns54BIXkVhFseSoSdDdqCdGefBBBDLjjnYP8Prj7ygpYWHO7iHOyxWjpUFmrBjwJkEp8I1tYuW/suoOCx+DPEjSm8cPROqF7IxCzDzv2ohf4CP/GPFRnxftO7P9WumUP7VGewuSDlIPX+jvdiYCltZkoIFIyEgOIUljq+W67PmHn1cC8WhUU61kJhGUIFweUM1hKBdS51wyBZJI/Wfr6b6A0NxWjuMe6P5dScdlbFe7fDzXBCMy0s9TAZdjIxvEzu62kizyKffAJMG0wEEF8rw+3umz+pP5eTls4hGUynu9OyIQoBGoRqIDZsZgOkidwBt4l2QtQQLbwvVQ3qZi0p28wxLpM7popg0sjBX3L2vFt7RHtFGjhcfNx8wmBYTvRoIIocDFhWvj1h0+w1FePyouJ4MxDQO2qyjylbB6NifQgjKfbidyUJysjtrhDdZKvCrJMDEEg4wC0nqPCCJ+TEPwpfbqL/9pK0eA4t125U12/BwZ7vBFTHQkrvl85JtHt4yFeSilsNsW3abJ/NDYvtNF8WUg=
  bucket: www.vefverdlaun.is
  skip_cleanup: true
  local-dir: dist
  acl: public-read
  cache_control: "no-cache"
  on:
    branch: master
    repo: svef/vefverdlaun.is
- provider: gcs
  access_key_id: GOOGZMKOTXLFVL5ERT2T
  secret_access_key:
    secure: YwzUJusZSJHuiNvCMlNgK710jZDT8hHmh2agrNhysKBkMgZYWlVkN1nQZDYZ8zR7qLXqEVBWzuXasAFGXE7/GESt/tT08pklXIT5Lj+VwHMqZChmu80OTBggYn1oop4V/S2aRAc0pgCfnuqsns54BIXkVhFseSoSdDdqCdGefBBBDLjjnYP8Prj7ygpYWHO7iHOyxWjpUFmrBjwJkEp8I1tYuW/suoOCx+DPEjSm8cPROqF7IxCzDzv2ohf4CP/GPFRnxftO7P9WumUP7VGewuSDlIPX+jvdiYCltZkoIFIyEgOIUljq+W67PmHn1cC8WhUU61kJhGUIFweUM1hKBdS51wyBZJI/Wfr6b6A0NxWjuMe6P5dScdlbFe7fDzXBCMy0s9TAZdjIxvEzu62kizyKffAJMG0wEEF8rw+3umz+pP5eTls4hGUynu9OyIQoBGoRqIDZsZgOkidwBt4l2QtQQLbwvVQ3qZi0p28wxLpM7popg0sjBX3L2vFt7RHtFGjhcfNx8wmBYTvRoIIocDFhWvj1h0+w1FePyouJ4MxDQO2qyjylbB6NifQgjKfbidyUJysjtrhDdZKvCrJMDEEg4wC0nqPCCJ+TEPwpfbqL/9pK0eA4t125U12/BwZ7vBFTHQkrvl85JtHt4yFeSilsNsW3abJ/NDYvtNF8WUg=
  bucket: dev.vefverdlaun.is
  skip_cleanup: true
  local-dir: dist
  acl: public-read
  cache_control: "no-cache"
  on:
    branch: develop
    repo: svef/vefverdlaun.is
